import Head from "next/head";
import Header from "../components/header";
import styles from "../styles/Home.module.scss";
import SectionOne from "../components/sectionOne";
import SectionTow from "../components/sectionTow";
import SectionThree from "../components/sectionThree";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>legaci</title>
        <meta name="description" content="Generated by legaci" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <SectionOne />
        <SectionTow />
        <SectionThree />
      </main>
      <footer className="footer bg-blue pt-4 pb-2">
        <div className="d-flex justify-content-center">
          <p>© 2022 Legaci. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
